export { default as Home } from './Home/Home.jsx'
export { default as Emergency } from './Services/Emergency.jsx'
export { default as BasicLifeSupport } from './Services/BasicLifeSupport.jsx'
export { default as Mortuary } from './Services/Mortuary.jsx'
export { default as ScheduleAmbulance } from './Services/ScheduleAmbulance.jsx'
export { default as AdvanceLifeSupport } from './Services/AdvanceLifeSupport.jsx'
